In [2]:
import numpy as np

<div style="background-color: #FFFFE0; padding: 10px; border: 1px solid #ddd;">
  <p style="color: #333333;"><b>Create Numpy Arrays</b></p>
</div>

In [3]:
arr = np.array([1,2,3])
arr2 = np.ones((1,1))
arr3 = np.zeros((2,2))
identity = np.eye(3)
linear_arr = np.linspace(0, 1, 5)


print(arr)
print(arr2)
print(arr3)
print(identity)
print(linear_arr)


[1 2 3]
[[1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.25 0.5  0.75 1.  ]


<div style="background-color: #FFFFE0; padding: 10px; border: 1px solid #ddd;">
  <p style="color: #333333;"><b>Transform Numpy Arrays</b></p>
</div>

<div style="background-color: #FFFFE0; padding: 10px; border: 1px solid #ddd;">
  <p style="color: #333333;"><b>Reshape</b></p>
</div>

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(-1, 1)
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Flatten

In [5]:
arr = np.array([[1,2,3], [4,5,6]])
flatten = arr.flatten()
print(flatten)

[1 2 3 4 5 6]


# Shape

In [6]:
arr = np.array([[1],[2]])
print(f"array shape: {arr.shape}")
print(f"array size: {arr.size}")
print(f"array dtype: {arr.dtype}")


arr = arr.astype(float)
print(f"array after dtype conversion: {arr}")

print(f"arr max: {arr.max()}")
print(f"arr min: {arr.min()}")
print(f"arr argmax: {arr.argmax()}")
print(f"arr argmin: {arr.argmin()}")
print(f"arr sum: {arr.sum()}")
print(f"arr mean: {arr.mean()}")
print(f"arr std: {arr.std()}")
print(f"arr var: {arr.var()}")





array shape: (2, 1)
array size: 2
array dtype: int64
array after dtype conversion: [[1.]
 [2.]]
arr max: 2.0
arr min: 1.0
arr argmax: 1
arr argmin: 0
arr sum: 3.0
arr mean: 1.5
arr std: 0.5
arr var: 0.25


# Transpose

In [7]:
arr = np.array([[1,2], [3,4]])
transposed = arr.transpose()
print(f"Transposed arr :")
print(f"{transposed}")

Transposed arr :
[[1 3]
 [2 4]]


# Element wise operations

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(f" The Dot product is : {arr1 @ arr2}")
print(f" The Dot product is : {np.dot(arr1 ,arr2)}")

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
 The Dot product is : 32
 The Dot product is : 32


<div style="background-color: #FFFFE0; padding: 10px; border: 1px solid #ddd;">
  <p style="color: #333333;"><b>Create a DataFrame</b></p>
</div>

In [9]:
import pandas as pd

df = pd.DataFrame(np.array([[1,2], [3,4]]), columns = ["A","B"])
df.head()

A  B
0  1  2
1  3  4

In [10]:
df["A"]

0    1
1    3
Name: A, dtype: int64

In [11]:
df[["A","B"]]

A  B
0  1  2
1  3  4

In [12]:
df.columns

Index(['A', 'B'], dtype='object')

In [13]:
df.iloc[0]

A    1
B    2
Name: 0, dtype: int64

In [14]:
df["A"] = df["A"] * 2

In [15]:
df.head()

A  B
0  2  2
1  6  4

In [21]:
df.drop("B", axis=1, inplace=True)
df.head()

A
0  2
1  6